export const FORM_PLACEHOLDERS = {
  businessName: "Business or trading name",
  phone: "10-digit mobile number",
  email: "name@example.com",
  addressLine1: "Building, street, area",
  addressLine2: "Landmark or suite (optional)",
  pinCode: "6-digit PIN code",
  city: "City or district",
  state: "Select state",
  gstin: "15-character GSTIN",
  productName: "Product or service name",
  sku: "SKU or item code",
  category: "Category (optional)",
  price: "0.00",
  quantity: "1",
  rate: "0.00",
  discount: "0.00",
  reference: "UPI ref, cheque no., or transfer note",
  memo: "Short description or memo",
  vendor: "Vendor or payee name",
  description: "What was purchased or paid for",
  notes: "Internal notes (optional)",
  hsnSac: "4–8 digit HSN/SAC",
  fileHint: "PDF, PNG, or JPG up to 10 MB",
} as const;
